<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Common\" />
    <None Remove="Common\Interfaces\" />
    <None Remove="Common\Behaviours\" />
    <None Remove="Common\Exceptions\" />
    <None Remove="Common\Models\" />
    <None Remove="Common\Security\" />
    <None Remove="ChatbotUseCases\" />
    <None Remove="ChatbotUseCases\Queries\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Common\Interfaces\" />
    <Folder Include="Common\Behaviours\" />
    <Folder Include="Common\Exceptions\" />
    <Folder Include="Common\Models\" />
    <Folder Include="Common\Security\" />
    <Folder Include="ChatbotUseCases\" />
    <Folder Include="ChatbotUseCases\Queries\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MagellanGPT.Domain\MagellanGPT.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Azure.AI.OpenAI" Version="1.0.0-beta.5" />
    <PackageReference Include="SonarAnalyzer.CSharp" Version="9.20.0.85982">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.2" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\SonarLint.xml">
      <Link>SonarLint.xml</Link>
    </None>
  </ItemGroup>
</Project>
