<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Common\" />
    <None Remove="Common\Interfaces\" />
    <None Remove="Common\Behaviours\" />
    <None Remove="Common\Exceptions\" />
    <None Remove="Common\Models\" />
    <None Remove="Common\Security\" />
    <None Remove="ChatbotUseCases\" />
    <None Remove="ChatbotUseCases\Queries\" />
    <None Remove="ChatbotUseCases\Commands\" />
    <None Remove="ChatbotUseCases\Commands\CreateAICompletion\" />
    <None Remove="RagUseCases\Queries\" />
    <None Remove="RagUseCases\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Common\Interfaces\" />
    <Folder Include="Common\Behaviours\" />
    <Folder Include="Common\Exceptions\" />
    <Folder Include="Common\Models\" />
    <Folder Include="Common\Security\" />
    <Folder Include="ChatbotUseCases\" />
    <Folder Include="ChatbotUseCases\Queries\" />
    <Folder Include="ChatbotUseCases\Commands\" />
    <Folder Include="ChatbotUseCases\Commands\CreateAICompletion\" />
    <Folder Include="RagUseCases\Queries\" />
    <Folder Include="RagUseCases\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MagellanGPT.Domain\MagellanGPT.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="SonarAnalyzer.CSharp" Version="9.20.0.85982">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.2" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.4.0" />
    <PackageReference Include="Microsoft.KernelMemory.DataFormats.AzureAIDocIntel" Version="0.32.240307.3" />
    <PackageReference Include="UglyToad.PdfPig" Version="1.7.0-custom-5" />
    <PackageReference Include="UglyToad.PdfPig.DocumentLayoutAnalysis" Version="1.7.0-custom-5" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.AzureAISearch" Version="1.4.0-alpha" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\SonarLint.xml">
      <Link>SonarLint.xml</Link>
    </None>
  </ItemGroup>
</Project>
