<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Persistence\" />
    <None Remove="Identity\" />
    <None Remove="OpenAI\" />
    <None Remove="Persistence\Configurations\" />
    <None Remove="KeyVault\" />
    <None Remove="Constants\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Persistence\" />
    <Folder Include="Identity\" />
    <Folder Include="OpenAI\" />
    <Folder Include="Persistence\Configurations\" />
    <Folder Include="KeyVault\" />
    <Folder Include="Constants\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Cosmos" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="8.0.2" />
    <PackageReference Include="SonarAnalyzer.CSharp" Version="9.20.0.85982">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.6.0" />
    <PackageReference Include="Azure.Security.KeyVault.Certificates" Version="4.6.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.4.0" />
    <PackageReference Include="Microsoft.KernelMemory.Core" Version="0.34.240313.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MagellanGPT.Application\MagellanGPT.Application.csproj" />
    <ProjectReference Include="..\MagellanGPT.Shared\MagellanGPT.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\SonarLint.xml">
      <Link>SonarLint.xml</Link>
    </None>
  </ItemGroup>
</Project>
